market/applications/caja/urls.py
#
from django.urls import path
from . import views

app_name = "caja_app"

urlpatterns = [
    path(
        'cierre-caja/index/', 
        views.ReporteCierreCajaView.as_view(),
        name='caja-index',
    ),
    path(
        'cierre-caja/cerrar/', 
        views.ProcesoCerrarCajaView.as_view(),
        name='caja-cerrar',
    ),
]

market/applications/venta/urls.py
#
from django.urls import path
from . import views

app_name = "venta_app"

urlpatterns = [
    path(
        'venta/index/', 
        views.AddCarView.as_view(),
        name='venta-index',
    ),
    # path(
    #     'carshop/update/<pk>/', 
    #     views.CarShopUpdateView.as_view(),
    #     name='carshop-update',
    # ),
    path(
        'carshop/update/<pk>/', 
        views.CarShopUpdateView.as_view(),
        name='carshop-update',
    ),
    path(
        'carshop/delete/<pk>/', 
        views.CarShopDeleteView.as_view(),
        name='carshop-delete',
    ),
    path(
        'carshop/list/', 
        views.ListCarShopView.as_view(),
        name='carshop-list',
    ),
    path(
        'carshop/delete/<pk>/', 
        views.CarShopDeleteView.as_view(),
        name='carshop-delete',
    ),
    path(
        'carshop/delete-all/', 
        views.CarShopDeleteAll.as_view(),
        name='carshop-delete_all',
    ),
    path(
        'venta/simple/', 
        views.ProcesoVentaSimpleView.as_view(),
        name='venta-simple',
    ),
    path(
        'venta/voucher/', 
        views.ProcesoVentaVoucherView.as_view(),
        name='venta-voucher',
    ),
    # path(
    #     'venta/voucher-pdf/<pk>/', 
    #     views.VentaVoucherPdf.as_view(),
    #     name='venta-voucher_pdf',
    # ),
    path(
        'venta/ultimas-ventas/', 
        views.SaleListView.as_view(),
        name='venta-list',
    ),
    path(
        'venta/delete/<pk>/', 
        views.SaleDeleteView.as_view(),
        name='venta-delete',
    ),
    path(
        'venta/', 
        views.ProcesoVenta.as_view(),
        name='venta',
    ),
    path(
        'venta/pdf/<pk>/', 
        views.VentaPdf.as_view(),
        name='venta-pdf',
    ),
]

market/market/urls.py
"""
Proyecto Final
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

market/applications/caja/models.py
from django.db import models
from django.conf import settings

#
from model_utils.models import TimeStampedModel

# local apps
from applications.producto.models import Product

#
# from .managers import SaleDetailManager


class CloseBox(TimeStampedModel):
    """
        Representa los cierres de caja
    """

    date_close = models.DateTimeField(
        'Fecha de Cierre',
    )
    count = models.PositiveIntegerField(
        'Cantidad de ventas'
    )
    amount = models.DecimalField(
        'Monto total en ventas', 
        max_digits=10, 
        decimal_places=2
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='cajero',
        related_name="close_user",
    )

    class Meta:
        verbose_name = 'Cierre Caja'
        verbose_name_plural = 'Cirres de Caja'

    def __str__(self):
        return str(self.user.full_name) + ' - ' + str(self.date_close)

market/applications/producto/models.py
# third-party
from model_utils.models import TimeStampedModel
# Django
from django.db import models
# local
from .managers import ProductManager

class Provider(TimeStampedModel):
    """
        Proveedor de Producto
    """

    name = models.CharField(
        'Razon Social', 
        max_length=100
    )
    email = models.EmailField(
        blank=True, 
        null=True
    )
    phone = models.CharField(
        'telefonos',
        max_length=40,
        blank=True,
    )
    rif = models.CharField(
        'RIF',
        max_length=10,
        blank=True,
    )


    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'

    def __str__(self):
        return self.name


class Product(TimeStampedModel):
    """
        Producto
    """

    UNIT_CHOICES = (
        ('0', 'Kilogramos'),
        ('1', 'Litros'),
        ('2', 'Unidades'),
    )

    code = models.CharField(
        max_length=13,
        unique=True
    )
    name = models.CharField(
        'Nombre', 
        max_length=40
    )
    description = models.TextField(
        'descripcion del producto',
        blank=True,
    )
    unit = models.CharField(
        'unidad de medida',
        max_length=1,
        choices=UNIT_CHOICES, 
    )
    count = models.DecimalField(
        'cantidad en almacen',
        default=0,
        max_digits=7, 
        decimal_places=2
    )
    num_sale = models.PositiveIntegerField(
        'numero de ventas',
        default=0
    )
    anulate = models.BooleanField(
        'eliminado',
        default=False
    )

    #
    objects = ProductManager()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.name
    
class Carga(TimeStampedModel):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    provider = models.ForeignKey(
        Provider, 
        on_delete=models.CASCADE
    )
    purchase_price = models.DecimalField(
        'precio compra',
        max_digits=7, 
        decimal_places=2,
        default=0
    )
    sale_price = models.DecimalField(
        'precio venta',
        max_digits=7, 
        decimal_places=2
    )
    count = models.DecimalField(
        'cantidad',
        default=0,
        max_digits=7, 
        decimal_places=2
    )
    

    class Meta:
        verbose_name = 'Carga'
        verbose_name_plural = 'Cargas'

    def __str__(self):
        return self.product + ' ' + str(self.count)

market/applications/venta/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete, post_save
#
from model_utils.models import TimeStampedModel

# local apps
from applications.producto.models import Product
from applications.users.models import User
from applications.home.models import Cliente
#
from .managers import SaleManager, SaleDetailManager, CarShopManager
from .signals import update_stok_ventas_producto


class Sale(TimeStampedModel):
    """Modelo que representa a una Venta Global"""

    # tipo recibo constantes
    BOLETA = '0'
    FACTURA = '1'
    SIN_COMPROBANTE = '2'
    # tipo pago constantes
    TARJETA = '0'
    EFECTIVO = '1'
    CREDITO = '2'
    DIVISAS = '3'
    #
    TIPO_INVOCE_CHOICES = [
        (BOLETA, 'Boleta'),
        (FACTURA, 'Factura'),
        (SIN_COMPROBANTE, 'Sin Comprobante'),
    ]

    TIPO_PAYMENT_CHOICES = [
        (TARJETA, 'Tarjeta'),
        (EFECTIVO, 'Cash'),
        (CREDITO, 'Bono'),
        (DIVISAS, 'Otro'),
    ]
    code = models.CharField('Código', max_length=10, default='001')
    date_sale = models.DateTimeField(
        'Fecha de Venta',
    )
    count = models.PositiveIntegerField('Cantidad de Productos')
    amount = models.DecimalField(
        'Monto', 
        max_digits=10, 
        decimal_places=2
    )
    type_invoce = models.CharField(
        'TIPO',
        max_length=2,
        choices=TIPO_INVOCE_CHOICES
    )
    pay = models.BooleanField('Pagado', default=False)
    type_payment = models.CharField(
        'TIPO PAGO',
        max_length=2,
        choices=TIPO_PAYMENT_CHOICES
    )
    close = models.BooleanField(
        'Venta cerrada',
        default=False
    )
    anulate = models.BooleanField(
        'Venta Anulada',
        default=False,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='cajero',
        related_name="user_venta",
    )
    cliente = models.CharField(
        'Cliente',
        max_length=20,
        blank=True,
        null=True
    )

    objects = SaleManager()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'ventas'

    def __str__(self):
        return 'Nº [' + str(self.id) + '] - ' + str(self.date_sale)



class SaleDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_sale'
    )
    sale = models.ForeignKey(
        Sale,
        on_delete=models.CASCADE, 
        verbose_name='Codigo de Venta',
        related_name='detail_sale'
    )
    count = models.FloatField('Cantidad')
    price_sale = models.DecimalField(
        'Precio Venta', 
        max_digits=10, 
        decimal_places=2
    )
    iva = models.DecimalField(
        'IVA', 
        max_digits=5,
        decimal_places=2
    )
    anulate = models.BooleanField(default=False)
    #
    total_mount = models.FloatField('Monto', default=0)
    objects = SaleDetailManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.name)


class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""
    code = models.CharField('Código', max_length=10, default='0')
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_car'
    )
    count = models.DecimalField(
        'Cantidad',
        max_digits=5,
        decimal_places=2
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_ventas_producto, sender=SaleDetail)

market/applications/venta/forms.py
from django import forms
#local
from .models import Sale
from applications.producto.models import Product


class VentaForm(forms.Form):
    code = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'v-model':'kword',
                'autocomplete':'off',
                'placeholder': 'Codigo',
                'class': 'input-group-field',
            }
        )
    )
    count = forms.FloatField(
        min_value=0.1,
        widget=forms.NumberInput(
            attrs = {
                'class': 'input-group-field',
                'step': 'any'
            }
        )
    )
    #
    def clean_count(self):
        count = self.cleaned_data['count']
        code = self.cleaned_data['code']
        producto = Product.objects.get(code=code)
        if count > producto.count:
            raise forms.ValidationError('La cantidad que desea vender es mayor a la cantidad existente en el almacen')
        if count < 0.1:
            raise forms.ValidationError('Ingrese una cantidad mayor a cero')

        return count
    
class CargaForm(forms.Form):
    code_table = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'Codigo de tarjeta',
                'class': 'input-group-field',
            }
        )
    )

class VentaVoucherForm(forms.Form):

    type_payment = forms.ChoiceField(
        required=False,
        choices=Sale.TIPO_PAYMENT_CHOICES,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )
    type_invoce = forms.ChoiceField(
        required=False,
        choices=Sale.TIPO_INVOCE_CHOICES,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )
    cliente = forms.CharField(
        required=False,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )
    venta = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'Codigo de tarjeta',
                'class': 'input-group-field',
            }
        )
    )

market/applications/caja/views.py
# django
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    View,
    TemplateView
)
#
from applications.venta.models import Sale, SaleDetail
from applications.users.mixins import VentasPermisoMixin
#
from .models import CloseBox
from .functions import detalle_ventas_no_cerradas


class ReporteCierreCajaView(VentasPermisoMixin, TemplateView):

    template_name = 'caja/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ventas_dia"] = detalle_ventas_no_cerradas
        context["total_vendido"] = Sale.objects.total_ventas_dia()
        context["total_anulado"] = Sale.objects.total_ventas_anuladas_dia()
        context["num_ventas_hoy"] = Sale.objects.ventas_no_cerradas().count()
        return context


class ProcesoCerrarCajaView(VentasPermisoMixin, View):

    def post(self, request, *args, **kwargs):
        # cerramos las ventas
        num_cerradas, total = Sale.objects.cerrar_ventas()
        if num_cerradas > 0:
            CloseBox.objects.create(
                date_close=timezone.now(),
                count=num_cerradas,
                amount= total,
                user=self.request.user
            )
        
        return HttpResponseRedirect(
            reverse(
                'caja_app:caja-index'
            )
        )
    

market/templates/venta/base_venta.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

market/templates/venta/caja.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <div class="cell grid-x grid-margin-x">
    <form class="cell small-7 input-group" method="POST">{% csrf_token %}
      <span class="input-group-label">COD/CAN:</span>
      <input type="text" id="code" name="code_table" placeholder="Código">
      {% for error in form.code.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
      <div class="input-group-button">
        <input type="submit" class="button secondary" value="Obtener">
      </div>
    </form>
    <div class="cell small-2">
      <a class="cell hollow button secondary" href="{% url 'venta_app:venta-list' %}">
        <i class="fi-trash"></i>
        <span>Ultimas Ventas</span>
      </a>
    </div>
  </div>

  <div class="grid-x grid-margin-x" style="padding: 1.5em;">
    <!-- contendor de la lista de productos en venta -->
    <div class="cell medium-8">
      <h5 class="cell"> Productos en Venta</h5>
      <table class="hover">
        <thead>
          <th width="200">COD</th>
          <th width="250">Nombres</th>
          <th width="120">Precio ($/)</th>
          <th width="100">Cantidad</th>
          <th>Acciones</th>
          <th></th>
        </thead>
        <tbody>
            {% for detalle in detalles_venta %}
            <tr>
              <td>{{ detalle.product.code }}</td>
              <td>{{ detalle.product.name }}</td>
              <td>{{ detalle.product.sale_price }}</td>
              <td>{{ detalle.count }} {{ detalle.product.get_unit_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- contiene los resultados resltantes -->
    <div class="cell medium-4">
      <div class="callout success" style="text-align: center;">
        <h5>Total a Cobrar:</h5>
        <h2> Bs/ {{ total_bs }} </h2>
        <h2> $/ {{ total }} </h2>
      </div>
      <button data-open="exampleModal1" class="cell button success" style="padding: 1.5em;">
        <i class="fi-print"></i>
          <span>Cobrar</span>
      </button>

      
      {% if venta %}
      <form class="cell" action="{% url 'venta_app:venta-delete' venta.id %}" method="POST">{% csrf_token %}
        <button type="submit" class="cell hollow button alert">
          <i class="fi-trash"></i>
          <span>Cancelar Venta</span>
        </button>
      </form>
      {% endif %}
        
    </div>

  </div>

  <!-- modal para el cobrar con comprobante de pago -->
  <div class="reveal" id="exampleModal1" data-reveal>
    <h3>Detalle del comprobante de pago</h3>
    <form action="{% url 'venta_app:venta' %}" class="grid-x grid-margin-x" 
      method="POST">{% csrf_token %}
      <div class="cell medium-6">
        <label>Tipo de Pago:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          <select name="type_payment" id="type_payment">
            <option value="0">Tarjeta</option>
            <option value="1">Cash</option>
            <option value="2">Bono</option>
            <option value="3">Otro</option>
          </select>
        </div>
        {% for error in form.type_payment.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Tipo de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-archive"></i></span>
          <select name="type_invoce" id="type_invoce">
            <option value="0">Boleta</option>
            <option value="1">Factura</option>
            <option value="2">Sin Comprobante</option>
          </select>
        </div>
        {% for error in form.type_invoce.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-9">
        <label>Cliente:</label>
        <div class="input-group">
          <input name="cliente" type="text">
        </div>
      </div>
      <input type="text" name="venta" id="venta" value="{{venta.id}}" style="display: none;">

      <button type="submit" class="cell success button">Pagar</button>
    </form>
  </div>

</div>

{% endblock panel-content %}

market/templates/venta/delete.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">¿Desea eliminar esta Venta?</h5>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" 
    action="{% url 'venta_app:venta-delete' sale.id %}" method="POST">
    {% csrf_token %}
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-divider">
              <h3>Monto: {{ sale.amount }}</h3>
            </div>
            <div class="card-section">
              <h4>ID: {{ sale.id }}</h4>
              <p>FECHA: {{ sale.date_sale }}</p>
              <p>CANTIDAD PRODUCTOS: {{ sale.count }}</p>
              <p>TIPO DE COMPROBANTE: {{ sale.get_type_invoce_display }}</p>
              <p>TIPO DE PAGO: {{ sale.get_type_payment_display }}</p>
            </div>
        </div>
    </div>
    
    <div class="cell medium-6">
      <button type="submit" class="alert button">Eliminar</button>
      <a href="{% url 'venta_app:venta-index' %}" class="primary button clear">Cancelar</a>
    </div>
  </form>
</div>

{% endblock panel-content %}

market/templates/venta/factura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Factura {{ venta.id }}</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        @page{
            size: 11cm 10.5cm;
            margin: 5px;
            border: 1px solid #000;
        }
        header{
            width: 100%;
            display: flex;
            text-align: center;
            font-size: 12px;
        }
            header .cabecera{
                width: 8cm;
                display: flex;
                flex-direction: column;
                justify-content: center;
            }
                header .cabecera h1{
                    font-size: 15px;
                }
                header .cabecera h2{
                    color: rgb(56, 0, 0);
                    font-size: 15px;
                    font-family: 'Constantia';
                    font-weight: bold;
                    font-style: italic;
                }
            header .fecha{
                width: 2.5cm;
                display: flex;
                flex-direction: column;
                justify-content: center;
                border-left: 1px solid #000;
            }
            header .fecha h4{
                border-bottom: 1px solid #000;
            }
        .cliente{
            display: flex;
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            padding: 5px 0;
        }
            .cliente span{
                font-size: 10px;
            }
            .cliente h3{
                width: 9cm;
                text-align: center;
            }

        table{
            width: 100%;
            text-align: center;
        }
            table td, table th{
                border-bottom: 1px solid #000;
                border-right: 1px solid #000;
            }

        footer{
            display: flex;
            justify-content: space-between;
            position: absolute;
            bottom: 0;
            width: 100%;
            border-top: 1px solid #000;
            text-align: right;
        }
            footer span, footer p{
                width: 50%;
            }
    </style>
</head>
<body>
    <header>
        <div class="cabecera">
            <h1>CARNICERÍA Y CHARCUTERÍA</h1>
            <h2>Las Hermanas Rivero R R, C.A.</h2>
            <h3>RIF. J-40186778-2</h3>
        </div>
        <div class="fecha">
            <h4>FECHA</h4>
            <span>{{ venta.date_sale|date:"d/m/Y" }}</span>
        </div>
    </header>
    <div class="cliente">
        <span>Nombre:</span>
        <h3>{{ venta.cliente }}</h3>
    </div>
    <table>
        <tr>
            <th scope="col">Cant.</th>
            <th scope="col">Descripción</th>
            <th scope="col">Valor Unitario</th>
            <th scope="col">Valor Total</th>
        </tr>
        {% for detalle in detalle_venta %}
            <tr>
                <td>{{ detalle.count }}</td>
                <td>{{ detalle.product.name }}</td>
                <td>{{ detalle.price_sale }}</td>
                <td>{{ detalle.total_mount }}</td>
            </tr>
        {% endfor %}
    </table>
    <footer>
        <span>TOTAL A PAGAR</span>
        <p>{{ venta.amount }}</p>
    </footer>

</body>
</html>
    

market/templates/venta/index.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

  <div id="app">
    <div class="cell grid-x grid-margin-x">
      <form class="cell small-7 input-group margin-x" method="POST" style="margin-bottom: 0;">{% csrf_token %}
        <span class="input-group-label">COD/CAN:</span>
        {{ form.code }}
        {{ form.count }}
        <div class="input-group-button">
          <input type="submit" class="button secondary" value="Agregar">
        </div>
      </form>
      {% for error in form.count.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="options"> <!-- Container. Resultados de autocompletado-->
      <ul v-for="articulo in lista_articulos" class="result-list">
          <li v-on:click="seleccionar(articulo.code)" class="text-result">
              <p>{$ articulo.code $} - {$ articulo.name $}, {$ articulo.count $} {$ articulo.get_unit_display $}</p>
          </li>
      </ul>
    </div>
  

    <div class="grid-x grid-margin-x" style="padding: 1.5em;">
      <!-- contendor de la lista de productos en venta -->
      <div class="cell medium-8">
        <h5 class="cell"> Productos en Venta</h5>
        <table class="hover">
          <thead>
            <th width="200">COD</th>
            <th width="250">Nombres</th>
            <th width="120">Precio de venta ($/)</th>
            <th width="100">Cantidad</th>
            <th width="120">Precio ($/)</th>
            <th>Acciones</th>
            <th></th>
          </thead>
          <tbody>
              <tr v-for="carro in lista_carrito" :key="carro.id">
                <td>{$ carro.product.code $}</td>
                <td>{$ carro.product.name $}</td>
                <td>{$ carro.product.sale_price $} $</td>
                <td>{$ carro.count $} {$ carro.product.get_unit_display $}</td>
                <td>{$ carro.product.sale_price * carro.count $} $</td>
                <td>
                  <button @click="abrirModalEditar(carro)" class="button primary"><i class="fi-pencil"></i></button>
                </td>
                <td>
                  <button @click="eliminarCarro(carro.id)" class="button alert"><i class="fi-trash"></i></button>
                </td>
              </tr>
          </tbody>
        </table>
      </div>


      <!-- contiene los resultados resltantes -->
      <div class="cell medium-4">
        <form class="cell" action="{% url 'venta_app:venta-simple' %}" method="POST">{% csrf_token %}
          <label for="code_table">Código de tarjeta:</label>
          {{ form_carga.code_table }}
          <button type="submit" class="cell button primery" style="padding: 1.5em;">
            <i class="fi-credit-card"></i>
            <span>Terminar Venta</span>
          </button>
        </form>
        <div class="callout success" style="text-align: center;">
          <h5>Total a Cobrar:</h5>
          <h2> Bs/ {$ actualizarTotal() * 30 $} </h2>
          <h2> $/ {$ actualizarTotal() $} </h2>
        </div>

        <br>

        <form class="cell" action="{% url 'venta_app:carshop-delete_all' %}" method="POST">{% csrf_token %}
          <button type="submit" class="cell hollow button alert">
            <i class="fi-trash"></i>
            <span>Limpiar Todo</span>
          </button>
        </form>
      </div>

    </div>

    <div id="modal" class="modal" v-show="mostrarModal">
      <div class="modal-content">
        <h2>Editar cantidad</h2>
        <form @submit.prevent="guardarCantidad">
          <p v-if="articuloSeleccionado">Cantidad actual: {$articuloSeleccionado.count$} {$articuloSeleccionado.product.get_unit_display$}</p>
          <label  for="cantidad">Nueva Cantidad:</label>
          <input type="number" v-model="nuevaCantidad" step="0.1" id="cantidad" required>
          <button type="submit" class="btnSave" @click="guardarCantidad(articuloSeleccionado.id, nuevaCantidad)">Guardar</button>
          <button type="button" class="btnCancel" @click="cerrarModal">Cancelar</button>
        </form>
      </div>
    </div>
  </div>

{% endblock panel-content %}
{% block js %}
<script src="{% static 'vue/vue.js' %}"></script>
<script src="{% static 'vue/axios.min.js' %}"></script>
<script src="{% static 'vue/apps/resultados.js' %}"></script>
{% endblock js %}

market/templates/venta/ventas.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
    <h3 class="cell" style="text-align: center;">Ultimas Ventas Registradas</h3>
    <div class="cell">
        <table>
            <thead>
                <th>Nomero</th>
                <th>Fecha</th>
                <th>Cantidad Productos</th>
                <th>Monto Total</th>
                <th>Anular</th>
            </thead>
            <tbody>
                {% for venta in ventas %}
                <tr>
                  <td>{{venta.id}}</td>
                  <td>{{venta.date_sale}}</td>
                  <td>{{venta.count}}</td>
                  <td>{{venta.amount}}</td>
                  <td>
                    <a href="{% url 'venta_app:venta-delete' venta.id %}" class="button alert"><i class="fi-x"></i></a>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock panel-content %}

market/templates/venta/voucher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Market DJ S.A</h3>
    <table>
        <tr>
            <td>N°</td><td>{{venta.id}}</td>
            <td>Fecha:</td><td>{{venta.date_sale}}</td>
        </tr>
        <tr>
            <td>Cantidad de Productos:</td><td>{{venta.count}}</td>
            <td>Monto Pagado:</td><td>{{venta.amount}}</td>
        </tr>
        <tr>
            <td>Tipo de Pago:</td><td>{{venta.get_type_invoce_display}}</td>
        </tr>
    </table>

    <h4>Poductos comprados:</h4>
    <ul>
        {% for producto in detalle_productos %}
          <li>{{ producto.product.name }} --- {{ producto.count }} --- {{ producto.price_sale}}</li>
        {% endfor %}
    </ul>
</body>
</html>